-- ============================================================
-- 01_schema.sql — Agente Hoteleiro (Hotel Sierra del Lago, Villa Carlos Paz)
--
-- Generado directamente desde el proyecto Supabase <project-ref> (no desde
-- archivos antiguos). Incluye: extensiones, tablas, índices, RLS y grants.
-- Ejecutar antes de 02_functions.sql.
-- ============================================================

-- ------------------------------------------------------------
-- Extensiones
-- ------------------------------------------------------------

create extension if not exists vector;

-- ------------------------------------------------------------
-- Tablas
-- ------------------------------------------------------------

-- Inventario de categorías de habitación del hotel.
create table if not exists public.tipos_habitacion (
  id            bigint generated by default as identity primary key,
  codigo        text not null unique,
  nombre        text not null,
  capacidad     integer not null,
  cantidad      integer not null,
  tarifa_noche  numeric not null,
  descripcion   text
);

-- Reservas. Una fila por reserva, con cantidad de habitaciones (no una fila
-- por habitación). Disponibilidad y precio se calculan siempre en SQL
-- (crear_reserva / consultar_disponibilidad), nunca por el LLM.
create table if not exists public.reservas (
  id                     bigint generated by default as identity primary key,
  codigo_reserva         text unique,
  tipo_codigo            text not null references public.tipos_habitacion (codigo),
  session_id             text,
  channel                text default 'chat',
  huesped_nombre         text,
  huesped_contacto       text,
  fecha_entrada          date not null,
  fecha_salida           date not null,
  cantidad_personas      integer not null default 1,
  noches                 integer,
  monto_total            numeric,
  monto_sena             numeric,
  monto_pagado           numeric default 0,
  status                 text not null default 'hold_sin_comprobante',
  expira_en              timestamptz,
  notas                  text,
  created_at             timestamptz default now(),
  updated_at             timestamptz default now(),
  cantidad_habitaciones  integer not null default 1
);

comment on column public.reservas.status is
  'hold_sin_comprobante (expira solo) | hold_comprobante (nunca expira solo, espera verificación humana) | confirmada | cancelada | expirada | no_show';

-- Comprobantes de pago reportados por el huésped. banco/titular/CBU del
-- comprobante van dentro de datos_extraidos (jsonb), no en columnas propias.
-- No hay índice único en nro_operacion salvo el parcial de abajo: la
-- deduplicación real la hace registrar_comprobante() con un exists() explícito.
create table if not exists public.pagos (
  id                bigint generated by default as identity primary key,
  reserva_id        bigint references public.reservas (id) on delete cascade,
  monto_reportado   numeric,
  metodo            text,
  nro_operacion     text,
  fecha_operacion   date,
  datos_extraidos   jsonb,
  archivo_url       text,
  status            text default 'reportado',
  observacion       text,
  created_at        timestamptz default now()
);

-- Base de conocimiento del hotel para RAG (pgvector).
create table if not exists public.documents_hotel (
  id         bigint generated by default as identity primary key,
  content    text,
  metadata   jsonb,
  embedding  vector(3072)
);

-- Búsqueda por similitud sobre documents_hotel, usada por la tool de RAG del agente.
create or replace function public.match_documents_hotel(
  query_embedding vector,
  match_count integer default 5,
  filter jsonb default '{}'::jsonb
)
returns table (id bigint, content text, metadata jsonb, similarity double precision)
language plpgsql
as $function$
begin
  return query
  select
    documents_hotel.id,
    documents_hotel.content,
    documents_hotel.metadata,
    1 - (documents_hotel.embedding <=> query_embedding) as similarity
  from documents_hotel
  where documents_hotel.metadata @> filter
  order by documents_hotel.embedding <=> query_embedding
  limit match_count;
end;
$function$;

-- Casos escalados a un humano. Hoy solo se inserta acá; nada la consulta
-- todavía (ver pendencias: notificación activa de escalación).
create table if not exists public.escalaciones (
  id               bigint generated by default as identity primary key,
  session_id       text,
  channel          text default 'chat',
  huesped_nombre   text,
  motivo           text,
  resumen          text,
  status           text default 'pendiente',
  created_at       timestamptz default now()
);

-- ------------------------------------------------------------
-- Índices
-- ------------------------------------------------------------

create index if not exists idx_reservas_busca
  on public.reservas (tipo_codigo, status, fecha_entrada, fecha_salida);

create index if not exists idx_reservas_session
  on public.reservas (session_id);

create index if not exists idx_pagos_reserva
  on public.pagos (reserva_id);

-- Único parcial: evita duplicar el mismo número de operación cuando viene
-- informado, pero no bloquea comprobantes que no lo traen (nro_operacion null).
create unique index if not exists idx_pagos_operacion_unica
  on public.pagos (nro_operacion) where (nro_operacion is not null);

-- ------------------------------------------------------------
-- Row Level Security
-- ------------------------------------------------------------

alter table public.tipos_habitacion  enable row level security;
alter table public.reservas          enable row level security;
alter table public.pagos             enable row level security;
alter table public.documents_hotel   enable row level security;
alter table public.escalaciones      enable row level security;

-- No existen policies en ninguna tabla. Con RLS activo y cero policies,
-- anon/authenticated quedan sin ningún acceso (ni lectura ni escritura),
-- aunque tengan GRANT a nivel de tabla. Solo service_role (que bypassa RLS
-- por definición) puede operar. El workflow n8n usa exclusivamente la
-- credencial service_role, así que nada queda expuesto por la Data API.

-- Event trigger que fuerza RLS en cualquier tabla nueva creada en public,
-- para que este modelo de seguridad no dependa de acordarse de activarla.
create or replace function public.rls_auto_enable()
returns event_trigger
language plpgsql
security definer
set search_path to 'pg_catalog'
as $function$
declare
  cmd record;
begin
  for cmd in
    select *
    from pg_event_trigger_ddl_commands()
    where command_tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      and object_type in ('table','partitioned table')
  loop
     if cmd.schema_name is not null and cmd.schema_name in ('public') and cmd.schema_name not in ('pg_catalog','information_schema') and cmd.schema_name not like 'pg_toast%' and cmd.schema_name not like 'pg_temp%' then
      begin
        execute format('alter table if exists %s enable row level security', cmd.object_identity);
        raise log 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      exception
        when others then
          raise log 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      end;
     else
        raise log 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     end if;
  end loop;
end;
$function$;

drop event trigger if exists ensure_rls;
create event trigger ensure_rls
  on ddl_command_end
  when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  execute function public.rls_auto_enable();

-- ------------------------------------------------------------
-- Grants — acceso operativo exclusivo de service_role
-- ------------------------------------------------------------

grant all on table public.tipos_habitacion   to service_role;
grant all on table public.reservas           to service_role;
grant all on table public.pagos              to service_role;
grant all on table public.documents_hotel    to service_role;
grant all on table public.escalaciones       to service_role;

grant execute on function public.match_documents_hotel(vector, integer, jsonb) to service_role;
